---
title: "Texevier"
author: "Nico Katzke"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Texevier}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

# Introduction 

This package helps a user set up an Elsevier template for writing academic journal reports in Rmarkdown. The setup requires very few lines of code and will get you up and running in _less than a minute_ (provided you have all the relevent dependencies installed - see below), with a fully working and good-to-go template. 

Using Texevier you can simply start writing your paper / thesis / phd in R.

## Dependencies Required

Make sure you have the following installed on your computer:

## Dependencies Required

Make sure you have the following installed on your computer:

* [R](http://cran.r-project.org/bin/windows/base/)
* [Rstudio](http://www.rstudio.com/)

## Optional (Should be installed automatically)

* [MikTex](http://miktex.org/download)

## Code

After installing all three at the top, simply run the following code:

```{r eval = FALSE}

    if (!require("devtools")) install.packages("devtools")
    library(devtools)
    devtools::install_github("Nicktz/Texevier")
    library(Texevier)
    # Input your directory as dir:
    dir <- "YOUR DIRECTORY HERE"
    create_template(directory = dir, template_name = "Template", ShowPDFatLaunch = FALSE)

```

This will automatically install all the needed files and components, and allow you to start working with an Elsevier template.

A template.Rmd file will be opened automatically from the directory provided, which contains all the needed notes on how to write an academic paper in R. I recommend going through that for a good reference before you start working.


## Motivation
Doing research in R allows you to verify your work easily. This template is designed to save the researcher time in terms of setting up a proper template for doing formal research. This is something which could feel daunting and can be time-consuming for even intermediate LaTeX  and R users. This package is intended to get you started in less than a minute.

Feel free to edit the templates and use this as a starting point for your own research. I suggest keeping the structure in the folder as is, but of course this is completely up to the researcher. 


Thanks to [Hanjo Odendaal](https://github.com/HanjoStudy) for adding some valuable code in the template creator as well.
